### ISSUE TITLE
Onboarding Wizards

### ISSUE THREAD

**Issue by postphotos** [ampproject/amp-wp#1288]
As a new user activating the AMP WordPress plugin for the first time, I need a user experience that helps me easily understand AMP, this plugin's features and what I can (and can't) do with it out of the box. With a streamlined experience, I should be able to activate (and understand) AMP with the least amount of steps necessary and the greatest amount of clarity possible.

- [x] AC1: ~Design a user flow that informs windows, screens, processes and messages they might receive.~ Duplicate #1359.
- [x] AC2: Evaluate this in comparison to the current user flow to see how to best roll out these features.
- [x] AC3: Suggest any new tweaks to existing settings pages, interfaces, etc. 
- [x] ~AC4: Suggest what to do with sites who run Classic Mode who can run Paired or Native modes.~  (moved to issue #1536 ) 
- [x] ~AC5: obtain the validation results for the most recently-published post and make them available to the user even before activating paired or classic modes.~ (suggested [here](https://github.com/Automattic/amp-wp/issues/1288#issuecomment-418892411).)(moved to issue #1537 ) 

_Placeholder ticket to be able to discuss new user experience questions for @postphotos, @jwold and anyone else who'd like to chime in._

Related #1006, #1273, #1254, #1235, #1359.

**Comment by jwold** [comment]
![img_f14381971e46-1](https://user-images.githubusercontent.com/3411173/43288410-942f7c5e-90dc-11e8-9ae7-257e42e76b68.jpeg)

Thoughts from call with Leo and I

**Comment by postphotos** [comment]
Hi @jwold - story and AC have been drafted here.

**Comment by jwold** [comment]
<img width="1366" alt="validation user journey" src="https://user-images.githubusercontent.com/3411173/44753577-6f7bb600-aad3-11e8-8bb6-cadf3ff41109.png">

Had a great discussion with @postphotos today to think through the implications of presenting options to the user when they need to decide whether to go with classic, paired, or native mode.

**Comment by westonruter** [comment]
Another AC is that we should make sure we obtain the validation results for the most recently-published post and make them available to the user even before activating paired or classic modes.  Actually, the validation status for each template type should be obtained and then this can be shown alongside each template in the hierarchy, as well as in some summary view with native/paired options.

**Comment by alcurrie** [comment]
@postphotos  and @kienstra - what would you think about me taking on the task of moving AC 4 and AC 5 as well as the AC that @westonruter  referenced re. obtaining 'validation results for the most recently-published post and make them available to the user even before activating paired or classic modes.' to the new v1.1 board?

**Comment by kienstra** [comment]
That sounds great, @alcurrie.

**Comment by postphotos** [comment]
#1384 asks the question of whether paired mode should be the default - linking to here.

**Comment by kienstra** [comment]
**Thanks For Opening New Issue**

Hi @alcurrie,
Thanks for opening #1536 and #1537 for this issue's AC4 and AC5. Now that all of the ACs on this issue are complete, what do you think about moving this to 'Ready for Merging'?

**Comment by alcurrie** [comment]
That makes sense to me.  @kienstra

**Comment by westonruter** [comment]
> <img alt="validation user journey" width="1366" src="https://user-images.githubusercontent.com/3411173/44753577-6f7bb600-aad3-11e8-8bb6-cadf3ff41109.png">

We'll need to revisit the redesigned settings screen to make the template modes more visually appealing.

**Comment by jwold** [comment]
Agreed! I would love to come back to this and spend some time making it more intuitive.

**Comment by swissspidy** [comment]
Also relates to #2427, which is about an onboarding wizard specifically for the Stories editor.

**Comment by westonruter** [comment]
Helpful to the onboarding flow would be the paired-browsing interface to navigate the site in a side-by-side view to see how well (or not) the site works in AMP: #3365.

**Comment by westonruter** [comment]
@samitron7 As an example for what another plugin does to prompt the user to enter an onboarding flow, here's what WooCommerce does upon activation:

> <img width="877" alt="Screen Shot 2019-10-13 at 15 06 45" src="https://user-images.githubusercontent.com/134745/66723201-341d7300-edcb-11e9-9142-705eea16463b.png">

Upon clicking “Run the Setup Wizard” the user sees these screens:

> ![image](https://user-images.githubusercontent.com/134745/66723216-5911e600-edcb-11e9-8fea-47f3814c3788.png)

> ![image](https://user-images.githubusercontent.com/134745/66723235-91b1bf80-edcb-11e9-825b-315b70cdf227.png)

> ![image](https://user-images.githubusercontent.com/134745/66723240-a726e980-edcb-11e9-999c-0800a8d64fcf.png)

> ![image](https://user-images.githubusercontent.com/134745/66723257-b9088c80-edcb-11e9-9493-c75bc3d71cd4.png)

Note also the link to [guided tour videos](https://docs.woocommerce.com/document/woocommerce-guided-tour-videos/) and information about [getting started](https://docs.woocommerce.com/documentation/plugins/woocommerce/getting-started/).

**Comment by westonruter** [comment]
Similarly, for Yoast, there is a prompt to access the configuration wizard in the admin bar and on the admin screen:

![image](https://user-images.githubusercontent.com/134745/66723458-39c88800-edce-11e9-80a7-675646db3599.png)

Opening the wizard takes you through these steps:

![image](https://user-images.githubusercontent.com/134745/66723469-4ea51b80-edce-11e9-94e5-04cc63efefd7.png)

![image](https://user-images.githubusercontent.com/134745/66723472-641a4580-edce-11e9-90a2-f9238d0d117d.png)

![image](https://user-images.githubusercontent.com/134745/66723488-97f56b00-edce-11e9-9081-51925228b62d.png)

![image](https://user-images.githubusercontent.com/134745/66723490-9f1c7900-edce-11e9-865d-4a8caf555a1d.png)

![image](https://user-images.githubusercontent.com/134745/66723493-a93e7780-edce-11e9-925f-164a2915c7bf.png)

![image](https://user-images.githubusercontent.com/134745/66723496-b0fe1c00-edce-11e9-9df6-0b96956e7cc3.png)

![image](https://user-images.githubusercontent.com/134745/66723507-c07d6500-edce-11e9-80d5-b55caff4ef9e.png)

**Comment by schlessera** [comment]
During the onboarding wizard, it would indeed be great to run the validation against multiple templates, and then provide a overview of the problems to expect and a smart suggestion of how to start (which mode, which templates, ...), and the best way to progress towards Transitional (which plugins to try to replace, ...).

Another goal that would be worthwhile to pursue with an onboarding wizard is to set the correct expectations for the user:
- that this is more of a development tool, not a 100% plug&play solution
- that we're eager to get feedback, and the ways in which this feedback can be provided

**Comment by amedina** [comment]
Related: https://github.com/ampproject/amp-wp/issues/4452

**Comment by jwold** [comment]
This issue has been resolved with other on boarding related issues.
