### ISSUE TITLE
Tooltips for Compatibility Tool

### ISSUE THREAD

**Issue by postphotos** [ampproject/amp-wp#1400]
**As a developer user debugging an error in the Compatibility Tool, I should have tooltips that hint at what given columns do to explain what they mean and how I should use that information.**

As a user gets stuck or confused, they should have both user-friendly hints and more verbose documentation at what the plugin does, why it's organized this way and how the tool intends to allow them to activate AMP quickly.

- [x] AC1: Based on #1361, #1362, #1363 and #1364 decide which columns need tooltips. Currently the Error by Type, Error by URL and Single screens all have tooltips on the header of the `Status` and `Detail` columns.
- [ ] AC2: For each tooltip, write copy and link to relevant URLs on the Plugin product site. (similar to #1401.)
- [ ] AC3: Implement each tooltip (per view, per column) based on what is decided in AC1/AC2.
- [ ] AC4: Re-implement to meet the spec of #1479.

**Comment by postphotos** [comment]
I've fleshed out the requirements for this story.

**Comment by jacobschweitzer** [comment]
Hey @postphotos , I've been working on #1362 and have gotten to the point I need some content for the tooltips and some clarification about how they should look. 

The only way I'm aware of to make tooltips in core WP is to use admin pointers. It'd look like this:

![https://cl.ly/3f43d4fae784](https://cl.ly/3f43d4fae784/Image%202018-09-10%20at%208.51.24%20PM.png)

How does that look? It opens when the user hovers over the "?" icon and closes when they click the dismiss link at the bottom.

**Comment by postphotos** [comment]
Thanks for sharing your WIP @jacobschweitzer!

While it does vary from the mocks that @jillchu had presented at an earlier state, I'm OK with this as it matches the design styles of the pointer from #1254, especially if it's leveraging a WP Core design pattern and if may be less engineering effort to complete.

@jwold - are you OK with this for a "tooltip" style?

**Comment by jwold** [comment]
@jacobschweitzer using this tooltip you mentioned should be perfect. Thank you! cc @postphotos

**Comment by johnwatkins0** [comment]
Moving this to code review. The PR is #1448.

**Comment by westonruter** [comment]
Tooltip text needs to still be finalized.

**Comment by kienstra** [comment]
**Minor Styling Issue**

The triangle of the 'tooltip' now points to the right of the `?`, but ideally, it should point to the `?`:

<img width="1301" alt="triangle-admin-pointer" src="https://user-images.githubusercontent.com/4063887/45972347-1b47f100-c001-11e8-9233-a586aeb86f20.png">

This looks to be the case wherever the tooltips are used:
* Invalid URLs page
* AMP Validation Error Index
* Single Error URL page (#1365)

**Comment by GaryJones** [comment]
@afercia @rianrietveld - what is the WP core approach for accessible tooltips? I don't recall seeing any other plugins using the admin pointers for this?

**Comment by kienstra** [comment]
Good question, @GaryJones!

**Comment by kienstra** [comment]
**Current 'Tooltip' Copy**

As @westonruter [mentioned](https://github.com/Automattic/amp-wp/issues/1400#issuecomment-423716588), the tooltip copy still needs to be determined. 

Here's the current copy:

*Status*

>An accepted validation error is one that will not block a URL from being served as AMP; the validation error will be sanitized, normally resulting in the offending markup being stripped from the response to ensure AMP validity.

<img width="1428" alt="status-tooltip" src="https://user-images.githubusercontent.com/4063887/45991175-40f8e880-c049-11e8-87bf-40f193790964.png">

*Details*
The 'tooltip' for Details is only a placeholder, and will still need copy.

**Comment by afercia** [comment]
@GaryJones the legacy core "pointers" aren't accessible. They've been discussed a few times in the last years and their usage generally discouraged. Reading in the comments above:

> It opens when the user hovers over the "?" icon 

how about keyboard users? how about communicating to users the "?" icon opens a sort of modal? I'd rather look at the `popover` implementation in Gutenberg, where a toggle button with a proper aria-label and visible button tooltip opens a floating panel that behaves like sort of a modal.

**Comment by kienstra** [comment]
**Possible 'Tooltip' Text**

*Status*

>"Rejected" and "New Rejected" will block the URL from being AMP, when in Paired mode, with "Automatically accept sanitization" unchecked

*Details*

>The parent element of where the error occurred

**Comment by jacobschweitzer** [comment]
These tooltips are finicky when positioning them. I've got it centered but in a different position. 

How does this look @postphotos @jwold  ?

<img width="1265" alt="screen shot 2018-09-25 at 8 13 43 pm" src="https://user-images.githubusercontent.com/3016425/46048426-adceba00-c0ff-11e8-8b8e-2ca304da2f8a.png">

**Comment by jwold** [comment]
@jacobschweitzer that looks like it should work from a positioning perspective. Thank you!

@afercia are you thinking it'd make more sense to use a popup like this?

![screen shot on 2018-09-26 at 09_19_34](https://user-images.githubusercontent.com/3411173/46093857-55360600-c16d-11e8-80cd-e1dad32dd131.png)

**Comment by afercia** [comment]
@jwold yes, that used to be called `popover` in Gutenberg :)

**Comment by kienstra** [comment]
**Request For Testing**

Hi @csossi,
Could you please test this on:
* [Invalid URLs](https://paired-ampconfdemo.pantheonsite.io/wp-admin/edit.php?post_type=amp_invalid_url)
* [AMP Validation Error Index](https://paired-ampconfdemo.pantheonsite.io/wp-admin/edit-tags.php?taxonomy=amp_validation_error&post_type=amp_invalid_url)
* [Single Error URL](https://paired-ampconfdemo.pantheonsite.io/wp-admin/post.php?post=749&action=edit) page

Every `?` icon should have a 'tooltip':
<img width="1137" alt="icons-tooltip" src="https://user-images.githubusercontent.com/4063887/46162578-54c16c00-c24e-11e8-8223-bc66b891ddaf.png">

**Comment by kienstra** [comment]
**Tooltip Copy**

Hi @jwold,
Happy birthday!

Could you please help with the copy for the 'Status' and 'Details' tooltips?

Here's some [possible copy](https://github.com/Automattic/amp-wp/issues/1400#issuecomment-424366184).

Thanks, and no need to do this today 😄

**Comment by csossi** [comment]
QA review: all tooltip popups appear onClick. Needs re-checking after copy finalized

**Comment by GaryJones** [comment]
The work seems to be progressing on using the **legacy** pointers. Did the fact they are **not accessible**, and **discouraged**, get ignored? That they may not support keyboard-only users, or tell screen-reader users what the behaviour is?

https://github.com/Automattic/amp-wp/issues/1400#issuecomment-424232988

**Comment by westonruter** [comment]
@GaryJones Yes, I believe the goal is to switch to using the Gutenberg popovers as soon as possible.

**Comment by westonruter** [comment]
Opened #1479 to switch pointers to popovers.

**Comment by kienstra** [comment]
**Request For Testing**

Hi @csossi,
Could you please test the [updated tooltip copy](https://github.com/Automattic/amp-wp/pull/1483#issuecomment-426508078) on [this staging site](https://paired-ampconfdemo.pantheonsite.io/wp-admin/edit-tags.php?taxonomy=amp_validation_error&post_type=amp_invalid_url)? 

Thanks!

**Comment by jwold** [comment]
@kienstra 

Followup up on feedback from @afercia I'd like to propose a design change to all the tooltips in the AMP Plugin, using popover as the base for the tooltips, similar to how Gutenberg now does this. 

<img width="856" alt="screen shot 2018-10-09 at 10 15 39 am" src="https://user-images.githubusercontent.com/3411173/46686205-6db21180-cbac-11e8-9ce5-697c4ecb730e.png">

It appears we can still do bold text, even increase font sizes (for inline headers, just not in blue backgrounds), and a "x" for dismiss. 

Here's an example of changes we could make to the AMP Plugin tooltips to be more in line with the design style of the popovers from Gutenberg. 

<img width="450" alt="screen shot 2018-10-09 at 10 17 31 am" src="https://user-images.githubusercontent.com/3411173/46686261-976b3880-cbac-11e8-8365-f8bb55d5b7d0.png">

My guess is that we could take more liberties in the style and design of these updated popovers to be more eye catching, but for now we should probably stick to what's been done in Gutenberg. 

cc @postphotos

**Comment by postphotos** [comment]
Updated to add AC4 (see #1479).

**Comment by kienstra** [comment]
**Question About ACs**

Hi @postphotos,
What do you think about removing AC4 (Re-implement to meet the spec of #1479)? Issue #1479 is on the `v1.1` project.

Side note: this issue is awaiting the product site to be able to link to it.

**Comment by kienstra** [comment]
**Status**

This issue is awaiting the product site to be able to link to it in the copy (AC2, AC3). There's no action needed now.

**Comment by kienstra** [comment]
**Moving Into To Do**

As there is no action needed now, I'm moving this into 'To Do.' 

When the product site has the URL ready, I'll add it to the tooltip, and request QA from @csossi.

**Comment by kienstra** [comment]
**Moving To 1.1 Project**

PR #1670 was the only remaining task for this issue planned for the 1.0 release. 

But the links in it aren't to a live site, so I'm moving this issue out of the [1.0 project](https://github.com/Automattic/amp-wp/projects/6#card-12728821).

**Comment by westonruter** [comment]
This should be tackled with #2316.

**Comment by jwold** [comment]
Weston > These popups are not the correct way to implement a tooltip from an accessibility perspective. Note that there are likely more considerations for accessibility. The primary focus for now though should be moving over to use the Gutenberg component that's responsible for tooltips (found in the edit post screen). That is part of the refactoring of these screens to be using React components. This will happen as part of that refactoring, and we may want to close this issue to say that it will be done as part of #2316.
