### ISSUE TITLE
[AMP Stories] Call to Action (CTA) Block

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#1963]
**Tasks:**

* [x] Add a way to insert a button within a CTA layer.
* [x] Disable block mover for CTA block (see #1897)
* [ ] Prevent adding more than one CTA block ~(using `supports: { multiple: false }`)~
* [x] Add shortcut to add a CTA block, disable shortcut if already present

**Reference:**

https://www.ampproject.org/docs/reference/components/amp-story#amp-story-cta-layer

**Comment by swissspidy** [comment]
Reading through the docs and checking out the [examples](https://github.com/ampproject/amphtml/blob/master/examples/amp-story/cta-layer-outlink.html), it looks like there can only be 1 link or button within the CTA layer.

Also, there can only be 1 CTA per page and its position is fixed. That means it should not be able to drag the CTA or anything.

**Comment by swissspidy** [comment]
From the spec>

> The `amp-story-cta-layer` allows mostly the same descendants as `amp-story-grid-layer`, and additionally allows `<a>` and `<button>` tags.

We could make the CTA block support inner blocks, but have a fixed template that only allows for 1 fixed button block in it. This way we get all the styling options for buttons for free.

**Comment by westonruter** [comment]
@swissspidy Can a block not have two separate `InnerBlocks` areas?

**Comment by westonruter** [comment]
> Reading through the docs and checking out the [examples](https://github.com/ampproject/amphtml/blob/master/examples/amp-story/cta-layer-outlink.html), it looks like there can only be 1 link or button within the CTA layer.

I don't think this is the case. This `amp-story-cta-layer` is not causing any validation errors:

```html
  <amp-story-cta-layer>
    <a href="https://www.ampproject.org" class="button">Outlink here!</a>
    <a href="https://www.ampproject.org" class="button">Outlink here!</a>
    <button on="tap:AMP.setState({})"></button>
    <button on="tap:AMP.setState({})"></button>
  </amp-story-cta-layer>
```

**Comment by swissspidy** [comment]
> Can a block not have two separate InnerBlocks areas?

Nope, not possible at the moment. See https://github.com/WordPress/gutenberg/blob/9a93e6a49fa86805e9e0a8bed6f102787e4d2e36/packages/block-editor/src/components/inner-blocks/README.md

> This amp-story-cta-layer is not causing any validation errors

Yeah the spec seems to contradict the docs / examples: https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/validator-amp-story.protoascii

**Comment by westonruter** [comment]
> Is this something we could achieve through the sanitizer? This way we don't need any complex logic on the editor side of things.

The sanitizer could indeed automatically move the `amp-story-cta-layer` to the very end of the `amp-story-page`. But that would result in the editor view looking different than the frontend. I recall @miina did work to force the CTA layer block to be at the very end. 

But if there can be more than one `InnerBlocks` in a story page, then instead of:

https://github.com/ampproject/amp-wp/blob/26edb6af69b675ebe1b874417116038acbfc0b19/assets/src/blocks/amp-story/edit.js#L189-L199

There could be something like:

```jsx
<div key="contents" style={ style }>
    { /* ... */ }
    
    <div class="amp-story-grid-layer">
        <InnerBlocks template={ TEMPLATE } allowedBlocks={ ALLOWED_CHILD_BLOCKS } />
    </div>

    <div class="amp-story-cta-layer">
        <InnerBlocks allowedBlocks={ ...ALLOWED_CHILD_BLOCKS, 'core/button' ] } />
    </div>
</div>
```

And the save function instead of:

https://github.com/ampproject/amp-wp/blob/26edb6af69b675ebe1b874417116038acbfc0b19/assets/src/blocks/amp-story/index.js#L81-L84

Be like:

```jsx
<amp-story-grid-layer template="vertical">
    <InnerBlocks.Content.Layer />
</amp-story-grid-layer>
{ InnerBlocks.Content.CTA && <amp-story-cta-layer><InnerBlocks.Content.CTA /></amp-story-cta-layer> }
```

**Comment by westonruter** [comment]
> Nope, not possible at the moment.

Alas, I see you're right:

> Note: A block can render at most a single `InnerBlocks` and `InnerBlocks.Content` element in `edit` and `save` respectively. To create distinct arrangements of nested blocks, create a separate block type which renders its own `InnerBlocks` and assign as the sole `allowedBlocks` type.

> Yeah the spec seems to contradict the docs / examples

So maybe the intended usage is that there only be one link or button. Maybe the validator isn't able to apply that constraint (which I'd be surprised by) or they didn't expect it to happen so they didn't add the constraint.

OK then. Well, then it sounds like what wen need is similar to the [`core/media-text`](https://github.com/WordPress/gutenberg/tree/master/packages/block-library/src/media-text) block, yes? It's just that instead of it being media followed by `InnerBlocks` we'd rather have `InnerBlocks` followed by a button or link? I'm not sure a button would even make sense in a user-authored story, so what if it just provides the link UI?

**Comment by miina** [comment]
>I recall @miina did work to force the CTA layer block to be at the very end.

Just for reference, [this was the last status of the previous CTA logic](https://github.com/ampproject/amp-wp/blob/amp-stories/blocks/amp-story/amp-story-cta-layer.js) which forced the CTA to be the last and also to appear just once and also not appear on the first page, however, it looks like the approach would be different now without the layer blocks.

**Comment by swissspidy** [comment]
> Well, then it sounds like what wen need is similar to the core/media-text block

I suppose so, yes. Can't think of a good UI for that at the moment though. I mean, ideally one would choose a URL, a text, and perhaps even a color, etc. That sounds more like a proper block to me...

**Comment by westonruter** [comment]
> That sounds more like a proper block to me...

Yeah, so wouldn't it be like `media-text`? In contrast with its [`edit` function](https://github.com/WordPress/gutenberg/blob/5b37ee70ef5a74c6c617828b30cd5e8dac8861da/packages/block-library/src/media-text/edit.js#L192-L199), the `amp-story-page` function could replace `this.renderMediaArea()` with `this.renderCTAArea()` which would could return a wrapped version of [`ButtonEdit`](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/button/edit.js), where it would could map the nested button's props to a `button` prop on the `amp-story-page` block. Would that work?

**Comment by swissspidy** [comment]
> Yeah, so wouldn't it be like `media-text` […] where it would could map the nested button's props to a `button` prop on the `amp-story-page` block. Would that work?

Sort of. It would work, but I don't particularly like adding so many props to the page block, especially when we think about future enhancements like page attachments. These would result in even more props. Plus the UI would be a bit different. In the Media + Text block the media area is always there, but that wouldn't be the case here.

Anyway, I'll try to build it like this as a PoC, and then we can decide whether to pursue that route or not.

**Comment by swissspidy** [comment]
> Plus the UI would be a bit different.

What comes to mind:

When selecting a page, one can set text and background colors in the block sidebar. When adding/editing a call to action, there would need to be additional color options for the CTA, which could look a bit odd.

**Comment by miina** [comment]
@swissspidy I'm closing this since you implemented this within #1993 which got merged.

Feel free to reopen this or create a follow-up issue if that's not correct information. Thanks!

**Comment by csossi** [comment]
verified in QA
